import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { Center } from '@chakra-ui/react'

import Search from './../components/Search'

export default function Home() {
  const router = useRouter()
  useEffect(() => {
    console.log(router.query)

  }, [router])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center h='60vh'>
        <Search />
      </Center>

    </div>
  )
}
